export const API_KEY = '7b115fce3267784b9a429773ec3ff484'
export const BASE_URL_SEARCH = 'https://api.themoviedb.org/3/search'
export const BASE_URL_MOVIE = 'https://api.themoviedb.org/3/movie'
export const BASE_URL_TV = 'https://api.themoviedb.org/3/tv'
export const BASE_URL_POSTER = 'https://image.tmdb.org/t/p/w500'
